package io.xkeen.mobile.app

import kotlinx.coroutines.test.runTest
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNull
import org.junit.Assert.assertThrows
import org.junit.Assert.assertTrue
import org.junit.Test

class OutboundsPortTest {
    @Test
    fun fragmentAndNodesResponsesMapWebPanelContract() {
        val index = parseOutboundsFragmentIndex(
            """
                {"ok":true,"dir":"/opt/etc/xray/configs","current":"04_outbounds.json",
                 "items":[{"name":"04_outbounds.json","size":120,"mtime":1000},
                          {"name":"05_routing.json","size":240}]}
            """.trimIndent(),
        )
        val snapshot = parseOutboundsSnapshot(
            """
                {"ok":true,"file":"04_outbounds.json","path":"/opt/etc/xray/configs/04_outbounds.json",
                 "nodes":[{"key":"nl-key","tag":"proxy-nl","name":"Netherlands","protocol":"vless",
                           "transport":"xhttp","security":"reality","host":"nl.example.net","port":443,
                           "subscription_node_name":"Amsterdam"}],
                 "node_latency":{"nl-key":{"status":"ok","delay_ms":47}}}
            """.trimIndent(),
        )

        assertEquals(listOf("04_outbounds.json"), index.items.map(OutboundsFragment::name))
        assertEquals("Amsterdam", snapshot.nodes.single().displayName)
        assertEquals("nl.example.net:443", snapshot.nodes.single().endpoint)
        assertEquals(47L, snapshot.nodes.single().latency?.delayMillis)
    }

    @Test
    fun activeResponseMapsRuntimeNodeIdentity() {
        val active = parseActiveOutboundSnapshot(
            """{"ok":true,"available":true,"active":{"key":"node-key","tag":"proxy-nl"},"message":"confirmed"}""",
        )

        assertTrue(active.available)
        assertEquals("node-key", active.key)
        assertEquals("proxy-nl", active.tag)
        assertEquals("confirmed", active.message)
    }

    @Test
    fun singleLinkSnapshotUsesServerManagedKindInsteadOfJsoncComment() {
        val first = parseOutboundLinkSnapshot(
            """{"ok":true,"file":"04_outbounds.json","path":"/opt/etc/xray/configs/04_outbounds.json","url":"vless://secret@example.com:443","outbound_tag":"my proxy","text":"{\"outbounds\":[]}"}""",
        )
        val second = parseOutboundLinkSnapshot(
            """{"ok":true,"file":"04_outbounds.json","path":"/opt/etc/xray/configs/04_outbounds.json","url":"vless://secret@example.com:443","outbound_tag":"my proxy","text":"// Generated by Xkeen UI subscription demo\n{\"outbounds\":[1]}"}""",
        )
        val managed = parseOutboundLinkSnapshot(
            """{"ok":true,"file":"04_outbounds.demo.json","path":"/opt/etc/xray/configs/04_outbounds.demo.json","url":"vless://secret@example.com:443","outbound_tag":"demo","managed_kind":"subscription","text":"{\"outbounds\":[1]}"}""",
        )

        assertEquals("vless://secret@example.com:443", first.url)
        assertEquals("my_proxy", first.outboundTag)
        assertTrue(first.sourceFingerprint.isNotBlank())
        assertFalse(first.sourceFingerprint == second.sourceFingerprint)
        assertNull(second.managedKind)
        assertEquals("subscription", managed.managedKind)
    }

    @Test
    fun saveLinkSendsSelectedFileCleanTagAndRestartPolicy() = runTest {
        val transport = RecordingOutboundsTransport(
            postResponses = ArrayDeque(
                listOf(response("""{"ok":true,"file":"04_outbounds.json","restarted":false}""")),
            ),
        )
        val port = WebPanelOutboundsPort(transport)

        val result = port.saveLink(
            baseUrl = "https://router.lan",
            filename = "04_outbounds.json",
            request = OutboundLinkSaveRequest(
                url = "vless://id@example.com:443?security=tls",
                outboundTag = "my proxy/ru",
                restart = false,
            ),
        )

        val request = transport.posts.single()
        val body = JSONObject(request.body.orEmpty())
        assertEquals("/api/outbounds?file=04_outbounds.json", request.endpoint)
        assertEquals("my_proxy_ru", body.getString("outbound_tag"))
        assertFalse(body.getBoolean("restart"))
        assertFalse(result.restarted)
    }

    @Test
    fun savePoolSendsSelectedFileEntriesAndPoolPolicies() = runTest {
        val transport = RecordingOutboundsTransport(
            postResponses = ArrayDeque(
                listOf(
                    response(
                        """{"ok":true,"updated":2,"file":"04_outbounds.cdn.json","replaced_pool":true,"tags":["nl_proxy","de-proxy","direct","block"],"restarted":false}""",
                    ),
                ),
            ),
        )
        val port = WebPanelOutboundsPort(transport)

        val result = port.savePool(
            baseUrl = "https://router.lan",
            filename = "04_outbounds.cdn.json",
            request = OutboundPoolSaveRequest(
                entries = listOf(
                    OutboundPoolSaveEntry(
                        tag = " nl proxy ",
                        url = " vless://id@nl.example:443?security=tls ",
                    ),
                    OutboundPoolSaveEntry(
                        tag = "de-proxy",
                        url = "trojan://secret@de.example:443?security=tls",
                    ),
                ),
                restart = true,
                replacePool = true,
                writeRaw = true,
                sockoptMark255 = true,
            ),
        )

        val request = transport.posts.single()
        val body = JSONObject(request.body.orEmpty())
        val entries = body.getJSONArray("entries")
        assertEquals("/api/xray/outbounds/proxies?file=04_outbounds.cdn.json", request.endpoint)
        assertEquals(2, entries.length())
        assertEquals("nl_proxy", entries.getJSONObject(0).getString("tag"))
        assertEquals("vless://id@nl.example:443?security=tls", entries.getJSONObject(0).getString("url"))
        assertTrue(body.getBoolean("restart"))
        assertTrue(body.getBoolean("replace_pool"))
        assertTrue(body.getBoolean("write_raw"))
        assertTrue(body.getBoolean("sockopt_mark_255"))
        assertEquals(2, result.updated)
        assertTrue(result.replacedPool)
        assertEquals(listOf("nl_proxy", "de-proxy", "direct", "block"), result.tags)
        assertTrue(result.restartRequested)
        assertFalse(result.restarted)
    }

    @Test
    fun pingRequestsUseSelectedFragmentAndNodeKeys() = runTest {
        val transport = RecordingOutboundsTransport(
            postResponses = ArrayDeque(
                listOf(
                    response("""{"ok":true,"node_key":"node-key","entry":{"status":"ok","delay_ms":38}}"""),
                    response(
                        """{"ok":true,"node_latency":{"node-key":{"status":"ok","delay_ms":39},"node-2":{"status":"error","error":"timeout"}}}""",
                    ),
                ),
            ),
        )
        val port = WebPanelOutboundsPort(transport)

        val single = port.ping("https://router.lan", "04_outbounds.cdn.json", "node-key")
        val bulk = port.pingAll(
            "https://router.lan",
            "04_outbounds.cdn.json",
            listOf("node-key", "node-2"),
        )

        assertEquals(38L, single.delayMillis)
        assertEquals(39L, bulk["node-key"]?.delayMillis)
        assertEquals("error", bulk["node-2"]?.status)
        assertEquals(
            "/api/xray/outbounds/nodes/ping?file=04_outbounds.cdn.json",
            transport.posts[0].endpoint,
        )
        assertEquals(
            "/api/xray/outbounds/nodes/ping-bulk?file=04_outbounds.cdn.json",
            transport.posts[1].endpoint,
        )
        val body = JSONObject(transport.posts[1].body.orEmpty())
        assertEquals(2, body.getJSONArray("node_keys").length())
        assertTrue(body.getBoolean("async"))
    }

    @Test
    fun bulkPingPollsAsyncJobUntilFinished() = runTest {
        val transport = RecordingOutboundsTransport(
            postResponses = ArrayDeque(
                listOf(response("""{"ok":true,"async":true,"job_id":"job-42","status":"queued"}""")),
            ),
            getResponses = ArrayDeque(
                listOf(
                    response("""{"ok":true,"job_id":"job-42","status":"running"}"""),
                    response(
                        """{"ok":true,"job_id":"job-42","status":"finished","result":{"ok":true,"node_latency":{"node-key":{"status":"ok","delay_ms":44}}}}""",
                    ),
                ),
            ),
        )
        val port = WebPanelOutboundsPort(transport)

        val result = port.pingAll(
            "https://router.lan",
            "04_outbounds.json",
            listOf("node-key"),
        )

        assertEquals(44L, result["node-key"]?.delayMillis)
        assertEquals(2, transport.gets.size)
        assertEquals("/api/xray/latency-jobs/job-42", transport.gets.first().endpoint)
    }

    @Test
    fun bulkPingKeepsPartialResultsWhenTopLevelOkIsFalse() {
        val result = parseBulkOutboundPing(
            """
                {"ok":false,"requested":2,"ok_count":1,"failed_count":1,
                 "node_latency":{"node-ok":{"status":"ok","delay_ms":51}},
                 "results":[
                   {"ok":true,"node_key":"node-ok","entry":{"status":"ok","delay_ms":51}},
                   {"ok":false,"node_key":"node-timeout","error":"timeout"}
                 ]}
            """.trimIndent(),
        )

        assertEquals(51L, result["node-ok"]?.delayMillis)
        assertEquals("error", result["node-timeout"]?.status)
        assertEquals("timeout", result["node-timeout"]?.message)
    }

    @Test
    fun bulkPingKeepsStructuredAllFailureResults() {
        val result = parseBulkOutboundPing(
            """
                {"ok":false,"requested":2,"ok_count":0,"failed_count":2,
                 "node_latency":{},
                 "results":[
                   {"ok":false,"node_key":"node-a","entry":{"error":"connection refused"}},
                   {"ok":false,"node_key":"node-b","error":"node not found"}
                 ]}
            """.trimIndent(),
        )

        assertEquals("error", result["node-a"]?.status)
        assertEquals("connection refused", result["node-a"]?.message)
        assertEquals("error", result["node-b"]?.status)
        assertEquals("node not found", result["node-b"]?.message)
    }

    @Test
    fun bulkPingRejectsUnstructuredFailure() {
        assertThrows(OutboundsException::class.java) {
            parseBulkOutboundPing("""{"ok":false,"error":"probe failed"}""")
        }
    }
}

private fun response(body: String) = CompanionHttpResponse(
    statusCode = 200,
    body = body,
    headers = emptyMap(),
    contentType = "application/json",
)

private class RecordingOutboundsTransport(
    private val postResponses: ArrayDeque<CompanionHttpResponse>,
    private val getResponses: ArrayDeque<CompanionHttpResponse> = ArrayDeque(),
) : CompanionHttpTransport {
    val posts = mutableListOf<CompanionHttpRequest>()
    val gets = mutableListOf<CompanionHttpRequest>()

    override suspend fun get(request: CompanionHttpRequest): CompanionHttpResponse {
        gets += request
        return getResponses.removeFirst()
    }

    override suspend fun post(request: CompanionHttpRequest): CompanionHttpResponse {
        posts += request
        return postResponses.removeFirst()
    }

    override suspend fun delete(request: CompanionHttpRequest): CompanionHttpResponse =
        throw AssertionError("Unexpected DELETE ${request.endpoint}")
}
