#!/bin/sh
# git pull --rebase поверх своих коммитов: та же проверка. После commit --amend не запускается.
[ "$1" = "rebase" ] || exit 0
case $0 in */*) dir=${0%/*} ;; *\\*) dir=${0%\\*} ;; *) dir=. ;; esac
. "$dir/keys-check.sh"
