from __future__ import annotations

import json
import os
import subprocess
import sys
import types
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STATIC_DIR = ROOT / "xkeen-ui" / "static"
BUILD_DIR = STATIC_DIR / "frontend-build"
MANIFEST_PATH = BUILD_DIR / ".vite" / "manifest.json"

EXPECTED_BUILD_ENTRIES = {
    "panel": "static/js/pages/panel.entry.js",
    "xkeen": "static/js/pages/xkeen.entry.js",
    "backups": "static/js/pages/backups.entry.js",
    "devtools": "static/js/pages/devtools.entry.js",
    "mihomo_generator": "static/js/pages/mihomo_generator.entry.js",
}

WRAPPER_HEADER = "// Auto-generated by scripts/sync_frontend_build_manifest.py"
WRAPPER_SUBHEADER = "// Build-managed ESM bridge entry. The canonical module graph lives under static/js."



SYNC_SCRIPT = ROOT / "scripts" / "sync_frontend_build_manifest.py"


def _expected_wrapper_text(source_entry: str) -> str:
    return "\n".join([
        WRAPPER_HEADER,
        WRAPPER_SUBHEADER,
        f"import '../../{source_entry[7:]}';",
        "",
    ])


def _write_minimal_sync_fixture(repo_root: Path, *, wrapper_text: str) -> Path:
    project_root = repo_root / "xkeen-ui"
    manifest_dir = project_root / "static" / "frontend-build" / ".vite"
    asset_dir = project_root / "static" / "frontend-build" / "assets"
    page_dir = project_root / "static" / "js" / "pages"
    manifest_dir.mkdir(parents=True, exist_ok=True)
    asset_dir.mkdir(parents=True, exist_ok=True)
    page_dir.mkdir(parents=True, exist_ok=True)

    source_entry = EXPECTED_BUILD_ENTRIES["panel"]
    (project_root / source_entry).write_text("export {};\n", encoding="utf-8")
    (manifest_dir / "manifest.json").write_text(
        json.dumps(
            {
                source_entry: {
                    "file": "assets/panel-test.js",
                    "isEntry": True,
                    "name": "panel",
                    "src": source_entry,
                }
            }
        ),
        encoding="utf-8",
    )
    wrapper_path = asset_dir / "panel-test.js"
    wrapper_path.write_text(wrapper_text, encoding="utf-8")
    return wrapper_path


def _load_manifest() -> dict[str, dict[str, object]]:
    return json.loads(MANIFEST_PATH.read_text(encoding="utf-8"))


def _get_build_wrapper_text(source_entry: str) -> str:
    manifest = _load_manifest()
    build_relpath = str(manifest[source_entry]["file"]).strip()
    build_path = BUILD_DIR / build_relpath
    assert build_path.is_file(), f"missing build asset for {source_entry}: {build_relpath}"
    return build_path.read_text(encoding="utf-8")


def _get_wrapper_statements(text: str) -> list[str]:
    lines = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line or line.startswith("//"):
            continue
        lines.append(line)
    return lines


def _import_ui_assets_module():
    fake_flask = types.ModuleType("flask")

    class _Flask:
        pass

    class _Response:
        pass

    fake_flask.Flask = _Flask
    fake_flask.Response = _Response
    fake_flask.current_app = None
    fake_flask.request = None
    fake_flask.send_file = lambda *args, **kwargs: None
    fake_flask.url_for = lambda *args, **kwargs: ""

    previous_flask = sys.modules.get("flask")
    previous_ui_assets = sys.modules.get("routes.ui_assets")
    sys.modules["flask"] = fake_flask
    sys.modules.pop("routes.ui_assets", None)

    try:
        import routes.ui_assets as ui_assets
    finally:
        if previous_flask is None:
            sys.modules.pop("flask", None)
        else:
            sys.modules["flask"] = previous_flask
        if previous_ui_assets is None:
            sys.modules.pop("routes.ui_assets", None)
        else:
            sys.modules["routes.ui_assets"] = previous_ui_assets

    return ui_assets


def test_frontend_build_manifest_still_matches_known_entrypoints():
    manifest = _load_manifest()

    assert set(manifest) == set(EXPECTED_BUILD_ENTRIES.values())

    for entry_name, source_entry in EXPECTED_BUILD_ENTRIES.items():
        manifest_entry = manifest[source_entry]
        build_relpath = str(manifest_entry["file"]).strip()
        build_path = BUILD_DIR / build_relpath

        assert manifest_entry.get("isEntry") is True
        assert manifest_entry.get("name") == entry_name
        assert manifest_entry.get("src") == source_entry
        assert build_relpath.startswith(f"assets/{entry_name}-")
        assert build_relpath.endswith(".js")
        assert build_path.is_file(), f"missing build asset for {entry_name}: {build_relpath}"


def test_frontend_build_wrappers_are_thin_import_only_bridge_entries():
    manifest = _load_manifest()

    for entry_name, source_entry in EXPECTED_BUILD_ENTRIES.items():
        text = _get_build_wrapper_text(source_entry)
        statements = _get_wrapper_statements(text)

        assert WRAPPER_HEADER in text, f"{entry_name} wrapper should advertise manifest sync ownership"
        assert WRAPPER_SUBHEADER in text, f"{entry_name} wrapper should describe the bridge contract"
        assert statements == [f"import '../../{source_entry[7:]}';"], (
            f"{entry_name} wrapper must stay import-only and point to the canonical source entrypoint"
        )
        assert "legacy_script_loader" not in text
        assert "bootLegacyEntry(" not in text
        assert "window." not in text
        assert "document." not in text
        assert "export " not in text
        assert "function " not in text
        assert "=>" not in text
        assert "await " not in text
        assert str(manifest[source_entry]["file"]).strip().startswith(f"assets/{entry_name}-")




def test_frontend_build_wrapper_sync_script_exists_and_passes_check_on_current_repo():
    assert SYNC_SCRIPT.is_file(), "manifest wrapper sync script must exist to formalize the stage 3 bridge"

    result = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--repo-root", str(ROOT), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stdout + result.stderr
    assert "Synced 5 wrapper file(s)." in result.stdout



def test_frontend_build_wrapper_sync_script_rewrites_outdated_wrapper(tmp_path):
    wrapper_path = _write_minimal_sync_fixture(
        tmp_path,
        wrapper_text="// stale wrapper\nconsole.log('drift');\n",
    )

    check_result = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--repo-root", str(tmp_path), "--check"],
        capture_output=True,
        text=True,
        check=False,
    )

    assert check_result.returncode == 1
    assert "MISMATCH xkeen-ui/static/frontend-build/assets/panel-test.js" in check_result.stdout

    sync_result = subprocess.run(
        [sys.executable, str(SYNC_SCRIPT), "--repo-root", str(tmp_path)],
        capture_output=True,
        text=True,
        check=False,
    )

    assert sync_result.returncode == 0, sync_result.stdout + sync_result.stderr
    assert wrapper_path.read_text(encoding="utf-8") == _expected_wrapper_text(EXPECTED_BUILD_ENTRIES["panel"])


def test_frontend_asset_helper_prefers_current_build_wrappers_when_they_are_modern():
    ui_assets = _import_ui_assets_module()
    previous = os.environ.get("XKEEN_UI_FRONTEND_SOURCE_FALLBACK")
    os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = "0"

    try:
        helper = ui_assets.FrontendAssetHelper(static_folder=str(STATIC_DIR))
        for entry_name, source_entry in EXPECTED_BUILD_ENTRIES.items():
            assert helper.build_entry_exists(entry_name), f"expected build entry for {entry_name}"
            assert helper.should_use_build_entry(entry_name), (
                f"{entry_name} should use manifest-managed build wrapper in the current project state"
            )
            build_path = BUILD_DIR / json.loads(MANIFEST_PATH.read_text(encoding='utf-8'))[source_entry]["file"]
            text = build_path.read_text(encoding="utf-8")
            assert f"import '../../{source_entry[7:]}';" in text
    finally:
        if previous is None:
            os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)
        else:
            os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = previous

def test_frontend_asset_helper_exposes_stage3_bridge_resolution_for_current_wrappers():
    ui_assets = _import_ui_assets_module()
    previous = os.environ.get("XKEEN_UI_FRONTEND_SOURCE_FALLBACK")
    os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = "0"

    try:
        helper = ui_assets.FrontendAssetHelper(static_folder=str(STATIC_DIR))
        manifest = _load_manifest()

        for entry_name, source_entry in EXPECTED_BUILD_ENTRIES.items():
            resolution = helper.get_build_bridge_resolution(entry_name)

            assert resolution.entry_name == entry_name
            assert resolution.source_filename == source_entry[7:]
            assert resolution.build_enabled is True
            assert resolution.manifest_entry == manifest[source_entry]
            assert resolution.build_filename == f"frontend-build/{manifest[source_entry]['file']}"
            assert resolution.build_path == str(BUILD_DIR / manifest[source_entry]["file"])
            assert resolution.build_exists is True
            assert resolution.fallback_reason is None
            assert resolution.should_use_build is True
            assert resolution.selected_filename == resolution.build_filename
            assert helper.resolve_frontend_page_entry_filename(entry_name) == resolution.build_filename
            assert helper.should_use_build_entry(entry_name) is resolution.should_use_build
    finally:
        if previous is None:
            os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)
        else:
            os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = previous



def test_frontend_asset_helper_stage8_contract_uses_dev_only_source_fallback_switch():
    ui_assets = _import_ui_assets_module()
    helper = ui_assets.FrontendAssetHelper(static_folder=str(STATIC_DIR))

    assert helper.source_fallback_env == "XKEEN_UI_FRONTEND_SOURCE_FALLBACK"
    assert not hasattr(ui_assets, "_BUILD_PAGES_ENV")


def test_frontend_asset_helper_requires_build_entries_in_build_only_mode(tmp_path):
    ui_assets = _import_ui_assets_module()
    previous = os.environ.get("XKEEN_UI_FRONTEND_SOURCE_FALLBACK")
    os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = "0"

    try:
        static_dir = tmp_path / "static"
        helper = ui_assets.FrontendAssetHelper(static_folder=str(static_dir))
        resolution = helper.get_build_bridge_resolution("panel")

        assert resolution.build_enabled is True
        assert resolution.build_filename is None
        assert resolution.build_exists is False
        assert resolution.fallback_reason == "missing_build_entry"
        assert resolution.source_fallback_enabled is False
        assert not resolution.should_use_build
        assert not resolution.should_use_source_fallback

        try:
            helper.resolve_frontend_page_entry_filename("panel")
        except RuntimeError as exc:
            message = str(exc)
        else:
            raise AssertionError("build-only mode must not silently fall back to source entrypoints")

        assert "Frontend build-only mode requires a valid build entry" in message
        assert "missing_build_entry" in message
    finally:
        if previous is None:
            os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)
        else:
            os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = previous


def test_frontend_asset_helper_allows_source_fallback_in_testing_app_context(tmp_path):
    ui_assets = _import_ui_assets_module()
    previous = os.environ.get("XKEEN_UI_FRONTEND_SOURCE_FALLBACK")
    if previous is None:
        os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)
    else:
        os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)

    previous_current_app = getattr(ui_assets, "current_app", None)
    ui_assets.current_app = types.SimpleNamespace(debug=False, testing=True, config={"TESTING": True})

    try:
        static_dir = tmp_path / "static"
        helper = ui_assets.FrontendAssetHelper(static_folder=str(static_dir))
        resolution = helper.get_build_bridge_resolution("panel")

        assert resolution.fallback_reason == "missing_build_entry"
        assert resolution.source_fallback_enabled is True
        assert resolution.should_use_source_fallback is True
        assert helper.resolve_frontend_page_entry_filename("panel") == "js/pages/panel.entry.js"
    finally:
        ui_assets.current_app = previous_current_app
        if previous is None:
            os.environ.pop("XKEEN_UI_FRONTEND_SOURCE_FALLBACK", None)
        else:
            os.environ["XKEEN_UI_FRONTEND_SOURCE_FALLBACK"] = previous


def test_frontend_asset_helper_exposes_normalized_page_config_contract():
    ui_assets = _import_ui_assets_module()
    helper = ui_assets.FrontendAssetHelper(static_folder=str(STATIC_DIR))

    config = helper.frontend_page_config(
        "panel",
        sections={"panelWhitelist": "routing files"},
        flags={
            "hasXray": "1",
            "hasMihomo": "0",
            "isMips": "false",
            "multiCore": "yes",
            "mihomoConfigExists": "on",
        },
        cores={
            "available": ("xray", "mihomo"),
            "detected": ("mihomo",),
            "uiFallback": "0",
        },
        files={"routing": Path("/tmp/05_routing.json")},
        file_manager={"rightDefault": "/tmp/mnt"},
        github={"repoUrl": "https://example.test/repo"},
        static={"base": "/static/", "version": 20260324},
        runtime={"debug": "yes"},
        terminal={
            "supportsPty": "1",
            "enableOptionalAddons": "0",
            "enableLigatures": "on",
            "enableWebgl": "false",
        },
    )

    assert config == {
        "contractVersion": 1,
        "page": "panel",
        "sections": {
            "panelWhitelist": "routing files",
            "devtoolsWhitelist": None,
        },
        "flags": {
            "hasXray": True,
            "hasMihomo": False,
            "isMips": False,
            "multiCore": True,
            "mihomoConfigExists": True,
        },
        "cores": {
            "available": ["xray", "mihomo"],
            "detected": ["mihomo"],
            "uiFallback": False,
        },
        "files": {
            "routing": "/tmp/05_routing.json",
            "inbounds": "",
            "outbounds": "",
            "mihomo": "",
        },
        "fileManager": {
            "rightDefault": "/tmp/mnt",
        },
        "github": {
            "repoUrl": "https://example.test/repo",
        },
        "static": {
            "base": "/static/",
            "version": "20260324",
        },
        "runtime": {
            "debug": True,
        },
        "terminal": {
            "supportsPty": True,
            "enableOptionalAddons": False,
            "enableLigatures": True,
            "enableWebgl": False,
        },
    }


def test_init_ui_assets_helpers_registers_page_config_template_global():
    ui_assets = _import_ui_assets_module()

    class FakeApp:
        def __init__(self):
            self.static_folder = str(STATIC_DIR)
            self.extensions = {}
            self.template_globals = {}

        def add_template_global(self, func, *, name=None):
            self.template_globals[name or getattr(func, '__name__', '')] = func

    app = FakeApp()
    helper = ui_assets.init_ui_assets_helpers(app)

    assert isinstance(helper, ui_assets.FrontendAssetHelper)
    assert app.extensions["xkeen_ui_assets"] is helper

    entry_global = app.template_globals["frontend_page_entry_url"]
    page_config_global = app.template_globals["frontend_page_config"]

    assert getattr(entry_global, "__self__", None) is helper
    assert getattr(entry_global, "__func__", None) is getattr(ui_assets.FrontendAssetHelper, "frontend_page_entry_url")
    assert getattr(page_config_global, "__self__", None) is helper
    assert getattr(page_config_global, "__func__", None) is getattr(ui_assets.FrontendAssetHelper, "frontend_page_config")
