import { test, expect } from '@playwright/test';


const accordions = [
  ['inbounds-header', 'inbounds-body'],
  ['routing-scenario-header', 'routing-scenario-body'],
  ['outbounds-header', 'outbounds-body'],
  ['routing-dat-header', 'routing-dat-body'],
  ['routing-backups-header', 'routing-backups-body'],
  ['routing-help-header', 'routing-help-body'],
];


async function mockRoutingCardData(page) {
  let statBatchCalls = 0;

  await page.route('**/api/fs/stat-batch', async (route) => {
    statBatchCalls += 1;
    if (statBatchCalls > 1) {
      await new Promise((resolve) => setTimeout(resolve, 700));
    }
    const request = route.request();
    const body = request.postDataJSON?.() || {};
    const paths = Array.isArray(body.paths) ? body.paths : [];
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        items: paths.map((path, index) => ({
          path,
          exists: true,
          size: 1024 * (index + 2),
          mtime: 1_777_777_777,
        })),
      }),
    });
  });

  await page.route('**/api/routing/geodat/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        installed: true,
        platform: { supported: true },
      }),
    });
  });

  await page.route('**/api/outbounds/fragments', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        dir: '/tmp/xray/configs',
        current: '04_outbounds.json',
        items: [{ name: '04_outbounds.json' }],
      }),
    });
  });

  const nodes = [
    {
      key: 'node-se',
      name: 'se-YYY-Sweden.e026',
      tag: 'cdn.example--se-YYY-Sweden.e026',
      protocol: 'vless',
      transport: 'xhttp',
      security: 'tls',
      host: '103.88.240.173',
      port: 443,
      detail: 'path=/api/v2/',
    },
    {
      key: 'node-de',
      name: 'de-Germany.0005',
      tag: 'cdn.example--de-Germany.0005',
      protocol: 'vless',
      transport: 'tcp',
      security: 'reality',
      host: 'germany-05.example',
      port: 443,
      detail: '',
    },
  ];

  const outboundsPayload = {
    ok: true,
    file: '04_outbounds.json',
    url: '',
    text: '// Generated by XKeen UI (outbounds pool)',
    config: { outbounds: nodes.map((node) => ({ tag: node.tag, protocol: node.protocol })) },
  };

  await page.route('**/api/outbounds', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(outboundsPayload),
    });
  });

  await page.route('**/api/outbounds?**', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(outboundsPayload),
    });
  });

  await page.route('**/api/xray/outbounds/nodes**', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        nodes,
        node_latency: {
          'node-se': { status: 'ok', delay_ms: 38 },
          'node-de': { status: 'error', error: 'timeout' },
        },
      }),
    });
  });

  await page.route('**/api/xray/outbounds/active**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        available: true,
        active: {
          key: 'node-se',
          tag: 'cdn.example--se-YYY-Sweden.e026',
          name: 'se-YYY-Sweden.e026',
          source: 'access',
        },
      }),
    });
  });
}


async function openPanel(page, theme) {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.addInitScript((nextTheme) => {
    localStorage.setItem('xkeen-theme', nextTheme);
    localStorage.setItem('xkeen.editor.engine', 'codemirror');
    localStorage.setItem('xkeen_inbounds_open', '0');
    localStorage.setItem('xkeen_outbounds_open', '0');
    localStorage.setItem('xk.routing.scenario.open.v1', '0');
    localStorage.setItem('xk.routing.dat.open.v3', '0');
    localStorage.setItem('xk.routing.backups.open.v1', '0');
    localStorage.setItem('xk.routing.help.open.v1', '0');
  }, theme);
  await mockRoutingCardData(page);
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
  await expect(page.locator('#view-routing')).toBeVisible();
}


async function collectNodeRowGeometry(page) {
  return page.evaluate(() => {
    const row = document.querySelector('#outbounds-nodes-list .xk-outbounds-node-item');
    const selectors = [
      '.xk-sub-node-name',
      '.xk-sub-node-protocol',
      '.xk-sub-node-endpoint-cell',
      '.xk-sub-node-health-cell',
      '.xk-sub-node-actions',
    ];
    const cells = selectors.map((selector) => {
      const node = row?.querySelector(selector);
      const rect = node?.getBoundingClientRect();
      return rect ? { left: rect.left, right: rect.right, top: rect.top, width: rect.width } : null;
    });
    const style = row ? getComputedStyle(row) : null;
    return {
      cells,
      columns: style?.gridTemplateColumns || '',
      overflow: style?.overflow || '',
      rowOverflow: row ? row.scrollWidth - row.clientWidth : 999,
      pageOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
    };
  });
}


test.describe('Operator Console Stage 3 routing cards', () => {
  for (const theme of ['dark', 'light']) {
    test(`accordions, statuses and node rows share one contract in ${theme}`, async ({ page }) => {
      await openPanel(page, theme);

      const closedBackgrounds = [];
      for (const [headerId, bodyId] of accordions) {
        const header = page.locator(`#${headerId}`);
        await expect(header).toHaveAttribute('role', 'button');
        await expect(header).toHaveAttribute('tabindex', '0');
        await expect(header).toHaveAttribute('aria-controls', bodyId);
        if ((await header.getAttribute('aria-expanded')) === 'true') {
          await header.evaluate((node) => node.click());
        }
        await expect(header).toHaveAttribute('aria-expanded', 'false');
        await expect(page.locator(`#${bodyId}`)).toBeHidden();
        await header.evaluate((node) => node.blur());
        closedBackgrounds.push({
          headerId,
          background: await header.evaluate((node) => getComputedStyle(node).backgroundColor),
        });
      }

      expect(
        new Set(closedBackgrounds.map((entry) => entry.background)).size,
        JSON.stringify(closedBackgrounds),
      ).toBe(1);

      const openBackgrounds = [];
      for (let index = 0; index < accordions.length; index += 1) {
        const [headerId, bodyId] = accordions[index];
        const header = page.locator(`#${headerId}`);
        await header.focus();
        await page.keyboard.press(index % 2 === 0 ? 'Enter' : 'Space');
        await expect(header).toHaveAttribute('aria-expanded', 'true');
        await expect(page.locator(`#${bodyId}`)).toBeVisible();
        openBackgrounds.push(await header.evaluate((node) => getComputedStyle(node).backgroundColor));
      }

      expect(new Set(openBackgrounds).size).toBe(1);
      expect(openBackgrounds[0]).not.toBe(closedBackgrounds[0].background);

      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'ok');
      await expect(page.locator('#routing-dat-geosite-meta')).toHaveAttribute('data-state', 'ok');
      const datVisual = await page.locator('#routing-dat-status').evaluate((node) => {
        const style = getComputedStyle(node);
        return {
          background: style.backgroundColor,
          borderTop: style.borderTopWidth,
          radius: style.borderRadius,
          color: style.color,
        };
      });
      expect(datVisual.background).toBe('rgba(0, 0, 0, 0)');
      expect(datVisual.borderTop).toBe('0px');
      expect(datVisual.radius).toBe('0px');

      await page.locator('#routing-dat-refresh-btn').click();
      await expect(page.locator('#routing-dat-refresh-btn')).toHaveAttribute('aria-busy', 'true');
      await expect(page.locator('#routing-dat-refresh-btn')).toBeDisabled();
      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'loading');
      await expect(page.locator('#routing-dat-refresh-btn')).toHaveAttribute('aria-busy', 'false');
      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'ok');

      const helpLink = page.locator('#routing-help-body .links a').first();
      const helpVisual = await helpLink.evaluate((node) => {
        const style = getComputedStyle(node);
        return { radius: style.borderRadius, background: style.backgroundColor };
      });
      expect(helpVisual.radius).toBe('0px');
      expect(helpVisual.background).toBe('rgba(0, 0, 0, 0)');

      const backupTableVisual = await page.locator('#backups-table').evaluate((node) => {
        const style = getComputedStyle(node);
        return { radius: style.borderRadius, background: style.backgroundColor, shadow: style.boxShadow };
      });
      expect(backupTableVisual.radius).toBe('0px');
      expect(backupTableVisual.background).toBe('rgba(0, 0, 0, 0)');
      expect(backupTableVisual.shadow).toBe('none');

      await expect(page.locator('#outbounds-nodes-list .xk-outbounds-node-item')).toHaveCount(2);
      await expect(page.locator('#outbounds-nodes-list .xk-outbounds-node-item').first()).toContainText('se-YYY-Sweden.e026');
      const desktopGeometry = await collectNodeRowGeometry(page);
      expect(desktopGeometry.cells.every(Boolean)).toBe(true);
      expect(desktopGeometry.cells.map((cell) => cell.left)).toEqual(
        [...desktopGeometry.cells].map((cell) => cell.left).sort((a, b) => a - b),
      );
      expect(desktopGeometry.columns.split(' ').length).toBe(5);
      expect(desktopGeometry.rowOverflow).toBeLessThanOrEqual(1);
      expect(desktopGeometry.pageOverflow).toBeLessThanOrEqual(1);

      await page.setViewportSize({ width: 390, height: 844 });
      await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
      const mobileGeometry = await collectNodeRowGeometry(page);
      expect(mobileGeometry.columns.split(' ').length).toBe(5);
      expect(mobileGeometry.overflow).toBe('hidden');
      expect(mobileGeometry.pageOverflow).toBeLessThanOrEqual(1);
    });
  }
});
