import { test, expect } from './fixtures.mjs';


const accordions = [
  ['inbounds-header', 'inbounds-body'],
  ['routing-scenario-header', 'routing-scenario-body'],
  ['outbounds-header', 'outbounds-body'],
  ['routing-dat-header', 'routing-dat-body'],
  ['routing-backups-header', 'routing-backups-body'],
  ['routing-help-header', 'routing-help-body'],
];


async function mockRoutingCardData(page) {
  let statBatchCalls = 0;

  await page.route('**/api/fs/stat-batch', async (route) => {
    statBatchCalls += 1;
    if (statBatchCalls > 1) {
      await new Promise((resolve) => setTimeout(resolve, 700));
    }
    const request = route.request();
    const body = request.postDataJSON?.() || {};
    const paths = Array.isArray(body.paths) ? body.paths : [];
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        items: paths.map((path, index) => ({
          path,
          exists: true,
          size: 1024 * (index + 2),
          mtime: 1_777_777_777,
        })),
      }),
    });
  });

  await page.route('**/api/routing/geodat/status', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        installed: true,
        platform: { supported: true },
      }),
    });
  });

  await page.route('**/api/outbounds/fragments', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        dir: '/tmp/xray/configs',
        current: '04_outbounds.json',
        items: [{ name: '04_outbounds.json' }],
      }),
    });
  });

  const nodes = [
    {
      key: 'node-se',
      name: 'se-YYY-Sweden.e026',
      tag: 'cdn.example--se-YYY-Sweden.e026',
      protocol: 'vless',
      transport: 'xhttp',
      security: 'tls',
      host: '103.88.240.173',
      port: 443,
      detail: 'path=/api/v2/',
    },
    {
      key: 'node-de',
      name: 'de-Germany.0005',
      tag: 'cdn.example--de-Germany.0005',
      protocol: 'vless',
      transport: 'tcp',
      security: 'reality',
      host: 'germany-05.example',
      port: 443,
      detail: '',
    },
  ];

  const outboundsPayload = {
    ok: true,
    file: '04_outbounds.json',
    url: '',
    text: '// Generated by XKeen UI (outbounds pool)',
    config: { outbounds: nodes.map((node) => ({ tag: node.tag, protocol: node.protocol })) },
  };

  await page.route('**/api/outbounds', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(outboundsPayload),
    });
  });

  await page.route('**/api/outbounds?**', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify(outboundsPayload),
    });
  });

  await page.route('**/api/xray/outbounds/nodes**', async (route) => {
    if (route.request().method() !== 'GET') {
      await route.fallback();
      return;
    }
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        nodes,
        node_latency: {
          'node-se': { status: 'ok', delay_ms: 38 },
          'node-de': { status: 'error', error: 'timeout' },
        },
      }),
    });
  });

  await page.route('**/api/xray/outbounds/active**', async (route) => {
    await route.fulfill({
      status: 200,
      contentType: 'application/json',
      body: JSON.stringify({
        ok: true,
        available: true,
        active: {
          key: 'node-se',
          tag: 'cdn.example--se-YYY-Sweden.e026',
          name: 'se-YYY-Sweden.e026',
          source: 'access',
        },
      }),
    });
  });
}


async function openPanel(page, theme) {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.addInitScript((nextTheme) => {
    localStorage.setItem('xkeen-theme', nextTheme);
    localStorage.setItem('xkeen.editor.engine', 'codemirror');
    localStorage.setItem('xkeen_inbounds_open', '0');
    localStorage.setItem('xkeen_outbounds_open', '0');
    localStorage.setItem('xk.routing.scenario.open.v1', '0');
    localStorage.setItem('xk.routing.dat.open.v3', '0');
    localStorage.setItem('xk.routing.backups.open.v1', '0');
    localStorage.setItem('xk.routing.help.open.v1', '0');
  }, theme);
  await mockRoutingCardData(page);
  await page.goto('/');
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme);
  await expect(page.locator('#view-routing')).toBeVisible();
}


async function collectNodeRowGeometry(page) {
  return page.evaluate(() => {
    const row = document.querySelector('#outbounds-nodes-list .xk-outbounds-node-item');
    const selectors = [
      '.xk-sub-node-name',
      '.xk-sub-node-protocol',
      '.xk-sub-node-endpoint-cell',
      '.xk-sub-node-health-cell',
      '.xk-sub-node-actions',
    ];
    const cells = selectors.map((selector) => {
      const node = row?.querySelector(selector);
      const rect = node?.getBoundingClientRect();
      return rect ? { left: rect.left, right: rect.right, top: rect.top, width: rect.width } : null;
    });
    const style = row ? getComputedStyle(row) : null;
    return {
      cells,
      columns: style?.gridTemplateColumns || '',
      overflow: style?.overflow || '',
      rowOverflow: row ? row.scrollWidth - row.clientWidth : 999,
      pageOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
    };
  });
}


async function collectDatCardGeometry(page) {
  return page.evaluate(() => {
    const card = document.querySelector('.routing-dat-item[data-kind="geosite"]');
    const fields = card?.querySelector('.routing-dat-fields-row');
    const dir = document.querySelector('#routing-dat-geosite-dir');
    const name = document.querySelector('#routing-dat-geosite-name');
    const combo = name?.closest('.routing-dat-combo');
    const found = document.querySelector('#routing-dat-geosite-found');
    const geoip = document.querySelector('.routing-dat-item[data-kind="geoip"]');
    const actions = card?.querySelector('.routing-dat-actions-inline');
    const inspector = card?.closest('.routing-side-card');
    const rect = (node) => {
      const value = node?.getBoundingClientRect();
      return value ? { top: value.top, bottom: value.bottom, left: value.left, right: value.right, width: value.width } : null;
    };
    return {
      fieldsColumns: fields ? getComputedStyle(fields).gridTemplateColumns.split(' ').length : 0,
      actionColumns: actions ? getComputedStyle(actions).gridTemplateColumns.split(' ').length : 0,
      dir: rect(dir),
      name: rect(name),
      combo: rect(combo),
      found: rect(found),
      geoip: rect(geoip),
      inspector: rect(inspector),
      foundPosition: found ? getComputedStyle(found).position : '',
      pageOverflow: document.documentElement.scrollWidth - document.documentElement.clientWidth,
    };
  });
}


test.describe('Operator Console Stage 3 routing cards', () => {
  for (const theme of ['dark', 'light']) {
    test(`accordions, statuses and node rows share one contract in ${theme}`, async ({ page }) => {
      await openPanel(page, theme);

      const closedBackgrounds = [];
      for (const [headerId, bodyId] of accordions) {
        const header = page.locator(`#${headerId}`);
        await expect(header).toHaveAttribute('role', 'button');
        await expect(header).toHaveAttribute('tabindex', '0');
        await expect(header).toHaveAttribute('aria-controls', bodyId);
        if ((await header.getAttribute('aria-expanded')) === 'true') {
          await header.evaluate((node) => node.click());
        }
        await expect(header).toHaveAttribute('aria-expanded', 'false');
        await expect(page.locator(`#${bodyId}`)).toBeHidden();
        await header.evaluate((node) => node.blur());
        closedBackgrounds.push({
          headerId,
          background: await header.evaluate((node) => getComputedStyle(node).backgroundColor),
        });
      }

      expect(
        new Set(closedBackgrounds.map((entry) => entry.background)).size,
        JSON.stringify(closedBackgrounds),
      ).toBe(1);

      const openBackgrounds = [];
      for (let index = 0; index < accordions.length; index += 1) {
        const [headerId, bodyId] = accordions[index];
        const header = page.locator(`#${headerId}`);
        await header.focus();
        await page.keyboard.press(index % 2 === 0 ? 'Enter' : 'Space');
        await expect(header).toHaveAttribute('aria-expanded', 'true');
        await expect(page.locator(`#${bodyId}`)).toBeVisible();
        openBackgrounds.push(await header.evaluate((node) => getComputedStyle(node).backgroundColor));
      }

      expect(new Set(openBackgrounds).size).toBe(1);
      expect(openBackgrounds[0]).not.toBe(closedBackgrounds[0].background);

      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'ok');
      await expect(page.locator('#routing-dat-geosite-meta')).toHaveAttribute('data-state', 'ok');
      const datVisual = await page.locator('#routing-dat-status').evaluate((node) => {
        const style = getComputedStyle(node);
        return {
          background: style.backgroundColor,
          borderTop: style.borderTopWidth,
          radius: style.borderRadius,
          color: style.color,
        };
      });
      expect(datVisual.background).toBe('rgba(0, 0, 0, 0)');
      expect(datVisual.borderTop).toBe('0px');
      expect(datVisual.radius).toBe('0px');

      const datClosedGeometry = await collectDatCardGeometry(page);
      expect(datClosedGeometry.fieldsColumns).toBe(2);
      expect(datClosedGeometry.dir.top).toBeCloseTo(datClosedGeometry.name.top, 1);
      expect(datClosedGeometry.dir.width).toBeGreaterThan(0);
      expect(datClosedGeometry.name.width).toBeGreaterThan(0);
      expect(datClosedGeometry.actionColumns).toBe(4);
      expect(datClosedGeometry.pageOverflow).toBeLessThanOrEqual(1);

      const datHelp = page.locator('.routing-dat-help-popover');
      await datHelp.locator('.xk-card-help-trigger').click();
      await expect(datHelp).toHaveAttribute('open', '');
      const datHelpGeometry = await page.evaluate(() => {
        const panel = document.querySelector('.routing-dat-help-popover .xk-card-help-panel');
        const inspector = document.querySelector('.routing-dat-card');
        const trigger = document.querySelector('.routing-dat-help-popover .xk-card-help-trigger');
        const rect = (node) => {
          const value = node?.getBoundingClientRect();
          return value ? { left: value.left, right: value.right, top: value.top, bottom: value.bottom } : null;
        };
        return {
          panel: panel ? {
            ...rect(panel),
            position: getComputedStyle(panel).position,
            zIndex: Number.parseInt(getComputedStyle(panel).zIndex, 10),
          } : null,
          inspector: rect(inspector),
          trigger: trigger ? {
            ...rect(trigger),
            radius: Number.parseFloat(getComputedStyle(trigger).borderRadius),
            background: getComputedStyle(trigger).backgroundImage,
          } : null,
        };
      });
      expect(datHelpGeometry.panel.position).toBe('absolute');
      expect(datHelpGeometry.panel.left).toBeGreaterThanOrEqual(datHelpGeometry.inspector.left - 1);
      expect(datHelpGeometry.panel.right).toBeLessThanOrEqual(datHelpGeometry.inspector.right + 1);
      expect(datHelpGeometry.panel.top).toBeGreaterThanOrEqual(datHelpGeometry.trigger.bottom);
      expect(datHelpGeometry.panel.zIndex).toBeGreaterThan(50);
      expect(datHelpGeometry.trigger.radius).toBeLessThanOrEqual(6);
      expect(datHelpGeometry.trigger.background).toBe('none');
      await datHelp.locator('.xk-card-help-trigger').click();
      await expect(datHelp).not.toHaveAttribute('open', '');

      await page.route('**/api/fs/list?**', async (route) => {
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify({
            ok: true,
            items: [
              { name: 'geosite_refilter.dat', type: 'file', size: 1024, mtime: 1_777_777_777 },
              { name: 'geosite_v2fly.dat', type: 'file', size: 2048, mtime: 1_777_777_778 },
            ],
          }),
        });
      });
      await page.locator('#routing-dat-refresh-btn').click();
      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'ok');
      await page.locator('#routing-dat-geosite-browse').click();
      await expect(page.locator('#routing-dat-geosite-browse')).toHaveAttribute('aria-expanded', 'true');
      await expect(page.locator('#routing-dat-geosite-found')).toBeVisible();
      await expect(page.locator('#routing-dat-geosite-found [role="option"]')).toHaveCount(2);
      const datOpenGeometry = await collectDatCardGeometry(page);
      expect(datOpenGeometry.foundPosition).toBe('static');
      expect(datOpenGeometry.found.bottom).toBeLessThanOrEqual(datOpenGeometry.geoip.top + 0.5);
      expect(datOpenGeometry.pageOverflow).toBeLessThanOrEqual(1);
      await page.keyboard.press('Escape');
      await expect(page.locator('#routing-dat-geosite-browse')).toHaveAttribute('aria-expanded', 'false');

      await page.locator('#routing-dat-refresh-btn').click();
      await expect(page.locator('#routing-dat-refresh-btn')).toHaveAttribute('aria-busy', 'true');
      await expect(page.locator('#routing-dat-refresh-btn')).toBeDisabled();
      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'loading');
      await expect(page.locator('#routing-dat-refresh-btn')).toHaveAttribute('aria-busy', 'false');
      await expect(page.locator('#routing-dat-status')).toHaveAttribute('data-state', 'ok');

      const helpLink = page.locator('#routing-help-body .links a').first();
      const helpVisual = await helpLink.evaluate((node) => {
        const style = getComputedStyle(node);
        return { radius: style.borderRadius, background: style.backgroundColor };
      });
      expect(helpVisual.radius).toBe('0px');
      expect(helpVisual.background).toBe('rgba(0, 0, 0, 0)');

      const backupTableVisual = await page.locator('#backups-table').evaluate((node) => {
        const style = getComputedStyle(node);
        return { radius: style.borderRadius, background: style.backgroundColor, shadow: style.boxShadow };
      });
      expect(backupTableVisual.radius).toBe('0px');
      expect(backupTableVisual.background).toBe('rgba(0, 0, 0, 0)');
      expect(backupTableVisual.shadow).toBe('none');

      await expect(page.locator('#outbounds-nodes-list .xk-outbounds-node-item')).toHaveCount(2);
      await expect(page.locator('#outbounds-nodes-list .xk-outbounds-node-item').first()).toContainText('se-YYY-Sweden.e026');
      const desktopGeometry = await collectNodeRowGeometry(page);
      expect(desktopGeometry.cells.every(Boolean)).toBe(true);
      // Server tiles share the two-column grammar used in the subscriptions
      // workbench: content on the left, diagnostic controls on the right.
      expect(desktopGeometry.columns.split(' ').length).toBe(2);
      // The inspector intentionally clips overly long cell labels. Its own
      // scroll width is not page overflow and does not make a row unusable.
      expect(desktopGeometry.pageOverflow).toBeLessThanOrEqual(1);

      await page.setViewportSize({ width: 390, height: 844 });
      await page.evaluate(() => new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(resolve))));
      const mobileGeometry = await collectNodeRowGeometry(page);
      expect(mobileGeometry.columns.split(' ').length).toBe(2);
      expect(mobileGeometry.overflow).toBe('hidden');
      expect(mobileGeometry.pageOverflow).toBeLessThanOrEqual(1);

      const mobileDatGeometry = await collectDatCardGeometry(page);
      expect(mobileDatGeometry.fieldsColumns).toBe(2);
      expect(mobileDatGeometry.actionColumns).toBe(2);
      expect(mobileDatGeometry.pageOverflow).toBeLessThanOrEqual(1);
    });
  }
});
