import { test, expect } from '@playwright/test';

const VALID_ROUTING = [
  '{',
  '  "routing": {',
  '    "domainStrategy": "AsIs",',
  '    "rules": [',
  '      {',
  '        "type": "field",',
  '        "outboundTag": "direct",',
  '        "ip": [',
  '          "1.1.1.1/32"',
  '        ]',
  '      }',
  '    ]',
  '  }',
  '}',
  '',
].join('\n');

const INVALID_ROUTING = VALID_ROUTING.replace('"1.1.1.1/32"', '"1.1.1.1/32",,');

const COMPLETION_ROUTING = [
  '{',
  '  "routing": {',
  '    ',
  '  }',
  '}',
  '',
].join('\n');

const RULE_KEY_COMPLETION_ROUTING = [
  '{',
  '  "routing": {',
  '    "rules": [',
  '      {',
  '        ',
  '      }',
  '    ]',
  '  }',
  '}',
  '',
].join('\n');

const RULE_VALUE_COMPLETION_ROUTING = [
  '{',
  '  "routing": {',
  '    "domainStrategy": "",',
  '    "rules": [',
  '      {',
  '        "network": ""',
  '      }',
  '    ]',
  '  }',
  '}',
  '',
].join('\n');

const UNKNOWN_RULE_FIELD_ROUTING = [
  '{',
  '  "routing": {',
  '    "rules": [',
  '      {',
  '        "type": "field",',
  '        "portt": "443",',
  '        "outboundTag": "block"',
  '      }',
  '    ]',
  '  }',
  '}',
  '',
].join('\n');

const SUBSCRIPTION_ROUTING = [
  '// Generated by XKeen UI subscriptions (routing sync)',
  '{',
  '  "observatory": {',
  '    "subjectSelector": ["cdn.pecan.run--WS_Germany", "vless-reality"],',
  '    "probeUrl": "https://www.google.com/generate_204",',
  '    "probeInterval": "60s",',
  '    "enableConcurrency": true',
  '  },',
  '  "routing": {',
  '    "rules": [',
  '      {',
  '        "type": "field",',
  '        "inboundTag": ["redirect", "tproxy"],',
  '        "balancerTag": "proxy",',
  '        "ruleTag": "xk_auto_leastPing"',
  '      }',
  '    ],',
  '    "balancers": [',
  '      {',
  '        "tag": "proxy",',
  '        "selector": ["cdn.pecan.run--WS_Germany", "vless-reality"],',
  '        "strategy": { "type": "leastPing" },',
  '        "fallbackTag": "direct"',
  '      }',
  '    ]',
  '  }',
  '}',
  '',
].join('\n');

async function waitForRoutingEditor(page) {
  await expect(page.locator('#view-routing')).toBeVisible();
  await page.waitForFunction(() => {
    return !!(
      window.XKeen &&
      window.XKeen.features &&
      window.XKeen.features.routing &&
      window.XKeen.features.routingShell &&
      typeof window.XKeen.features.routing.replaceEditorText === 'function' &&
      typeof window.XKeen.features.routingShell.getEditorInstance === 'function'
    );
  });
}

async function ensureCodeMirrorRouting(page) {
  const select = page.locator('#routing-editor-engine-select');
  await expect(select).toBeVisible();
  await select.selectOption('codemirror');

  await page.waitForFunction(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    const isCm6 = !!(editor && (
      editor.__xkeenCm6Bridge === true ||
      editor.__xkeen_cm6_bridge === true ||
      editor.backend === 'cm6'
    ));
    return !!(isCm6 && typeof editor.getSchema === 'function');
  });
}

async function replaceRoutingText(page, text) {
  await page.evaluate((nextText) => {
    window.XKeen.features.routing.replaceEditorText(nextText, {
      markDirty: false,
      reason: 'e2e-routing-schema',
      scrollTop: true,
    });
  }, text);
}

async function waitForRoutingSchema(page) {
  await page.waitForFunction(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    const schema = editor && typeof editor.getSchema === 'function' ? editor.getSchema() : null;
    return schema && schema.title === 'Xray Routing Fragment';
  });
}

async function waitForUiSettings(page) {
  await page.waitForFunction(() => {
    return !!window.XKeen?.ui?.settings?.isLoadedFromServer?.();
  });
}

async function findTokenCenter(page, needle) {
  const box = await page.evaluate((token) => {
    const root = document.querySelector('.cm-content');
    if (!root) return null;
    const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
    let node = walker.nextNode();
    while (node) {
      const index = String(node.nodeValue || '').indexOf(token);
      if (index >= 0) {
        const range = document.createRange();
        range.setStart(node, index);
        range.setEnd(node, index + token.length);
        const rect = range.getBoundingClientRect();
        range.detach();
        if (rect.width || rect.height) {
          return {
            x: rect.left + rect.width / 2,
            y: rect.top + rect.height / 2,
          };
        }
      }
      node = walker.nextNode();
    }
    return null;
  }, needle);

  expect(box, `token ${needle} should be rendered in CodeMirror`).toBeTruthy();
  return box;
}

async function hoverRenderedToken(page, needle) {
  const box = await findTokenCenter(page, needle);
  await page.mouse.move(box.x, box.y);
}

async function clearEditorTooltips(page) {
  await page.mouse.move(8, 8);
  await page.waitForTimeout(200);
}

async function tooltipText(page, selector) {
  return page.evaluate((css) => {
    return Array.from(document.querySelectorAll(css))
      .map((node) => String(node.textContent || ''))
      .join('\n');
  }, selector);
}

async function clickAutocompleteOption(page, label) {
  await page.locator('.cm-tooltip-autocomplete li').filter({ hasText: label }).first().click();
}

async function moveRoutingCursor(page, pos) {
  await page.evaluate(({ line, ch }) => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    editor.setCursor({ line, ch });
    editor.focus();
  }, pos);
}

async function moveRoutingCursorAfterText(page, needle) {
  await page.evaluate((target) => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    const value = editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
    const index = value.indexOf(target);
    if (index < 0) throw new Error(`Text not found in routing editor: ${target}`);
    const before = value.slice(0, index + target.length).split('\n');
    editor.setCursor({ line: before.length - 1, ch: before[before.length - 1].length });
    editor.focus();
  }, needle);
}

async function setSchemaHoverEnabled(page, enabled) {
  await page.evaluate((nextEnabled) => {
    window.XKeen?.ui?.settings?.patchLocal?.({
      editor: { schemaHoverEnabled: !!nextEnabled },
    });
  }, enabled);
  await page.waitForTimeout(200);
}

async function saveSchemaHoverEnabled(page, enabled) {
  await page.evaluate(async (nextEnabled) => {
    const api = window.XKeen?.ui?.settings;
    if (!api || typeof api.patch !== 'function') throw new Error('ui settings API missing');
    await api.patch({ editor: { schemaHoverEnabled: !!nextEnabled } });
  }, enabled);
  await page.waitForTimeout(250);
}

test('routing CodeMirror keeps JSONC diagnostics and exposes fragment schema help', async ({ page }) => {
  await page.goto('/');
  await waitForRoutingEditor(page);
  await ensureCodeMirrorRouting(page);
  await waitForRoutingSchema(page);
  await waitForUiSettings(page);
  await saveSchemaHoverEnabled(page, true);

  await replaceRoutingText(page, INVALID_ROUTING);

  await expect(page.locator('#routing-error')).toContainText(/JSON error|Недопустимый символ|Ожидается/);
  await expect
    .poll(() => page.evaluate(() => document.querySelectorAll('.cm-lintRange-error, .cm-lint-marker-error').length))
    .toBeGreaterThan(0);

  const diagnosticTarget = page.locator('.cm-lintRange-error, .cm-lint-marker-error').first();
  await diagnosticTarget.hover();
  await expect(page.locator('.cm-tooltip-lint')).toContainText(/Недопустимый символ|JSON|Ожидается/);
  await expect.poll(() => tooltipText(page, '.cm-tooltip-hover')).not.toContain('Правило маршрутизации');

  await replaceRoutingText(page, VALID_ROUTING);
  await clearEditorTooltips(page);
  await expect(page.locator('#routing-error')).toHaveText('');
  await expect
    .poll(() => page.evaluate(() => document.querySelectorAll('.cm-lintRange-error, .cm-lint-marker-error').length))
    .toBe(0);

  await replaceRoutingText(page, SUBSCRIPTION_ROUTING);
  await clearEditorTooltips(page);
  await expect(page.locator('#routing-error')).toHaveText('');
  await expect
    .poll(() => page.evaluate(() => document.querySelectorAll('.cm-lintRange-error, .cm-lint-marker-error').length))
    .toBe(0);

  await hoverRenderedToken(page, '"rules"');
  await expect(page.locator('.cm-tooltip-hover')).toContainText('Массив правил маршрутизации');
  await expect(page.locator('.cm-tooltip-hover')).toContainText('поля:');
  await expect(page.locator('.cm-tooltip-hover')).toContainText('outboundTag');

  await setSchemaHoverEnabled(page, false);
  await clearEditorTooltips(page);
  await hoverRenderedToken(page, '"rules"');
  await page.waitForTimeout(700);
  await expect.poll(() => tooltipText(page, '.cm-tooltip-hover')).not.toContain('Массив правил маршрутизации');
  await expect.poll(() => page.evaluate(() => document.querySelectorAll('.cm-tooltip-hover, .cm6-json-schema-hover').length)).toBe(0);
  await setSchemaHoverEnabled(page, true);
  await clearEditorTooltips(page);

  await replaceRoutingText(page, COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await setSchemaHoverEnabled(page, false);
  await moveRoutingCursor(page, { line: 2, ch: 4 });
  await page.keyboard.type('domainS');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('domainStrategy');
  await clickAutocompleteOption(page, 'domainStrategy');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"domainStrategy": "AsIs"');
  await expect.poll(() => page.evaluate(() => document.querySelectorAll('.cm-tooltip-hover, .cm6-json-schema-hover').length)).toBe(0);
  await setSchemaHoverEnabled(page, true);
  await clearEditorTooltips(page);

  await replaceRoutingText(page, COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await moveRoutingCursor(page, { line: 2, ch: 4 });
  await page.keyboard.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('domainStrategy');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('rules');

  await replaceRoutingText(page, RULE_KEY_COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await setSchemaHoverEnabled(page, false);
  await moveRoutingCursor(page, { line: 4, ch: 8 });
  await page.keyboard.type('inboundT');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('inboundTag');
  await clickAutocompleteOption(page, 'inboundTag');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"inboundTag": []');
  await expect.poll(() => page.evaluate(() => document.querySelectorAll('.cm-tooltip-hover, .cm6-json-schema-hover').length)).toBe(0);

  await replaceRoutingText(page, RULE_KEY_COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await moveRoutingCursor(page, { line: 4, ch: 8 });
  await page.keyboard.type('netw');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('network');
  await clickAutocompleteOption(page, 'network');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"network": ""');

  await replaceRoutingText(page, RULE_VALUE_COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await moveRoutingCursorAfterText(page, '"domainStrategy": "');
  await page.keyboard.type('IPIf');
  await page.keyboard.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('IPIfNonMatch');
  await clickAutocompleteOption(page, 'IPIfNonMatch');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"domainStrategy": "IPIfNonMatch"');

  await replaceRoutingText(page, VALID_ROUTING);
  await waitForRoutingSchema(page);
  await moveRoutingCursorAfterText(page, '"domainStrategy": "');
  await page.keyboard.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('IPIfNonMatch');
  await page.locator('.cm-tooltip-autocomplete li').filter({ hasText: 'IPIfNonMatch' }).first().click();
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"domainStrategy": "IPIfNonMatch",');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).not.toContain('AsIs');

  await replaceRoutingText(page, RULE_VALUE_COMPLETION_ROUTING);
  await waitForRoutingSchema(page);
  await moveRoutingCursorAfterText(page, '"network": "');
  await page.keyboard.type('u');
  await page.keyboard.press('Control+Space');
  await expect(page.locator('.cm-tooltip-autocomplete')).toContainText('udp');
  await clickAutocompleteOption(page, 'udp');
  await expect.poll(() => page.evaluate(() => {
    const maybeEditor = window.XKeen?.features?.routingShell?.getEditorInstance?.({ preferRaw: true });
    const editor = maybeEditor && maybeEditor.raw ? maybeEditor.raw : maybeEditor;
    return editor && typeof editor.getValue === 'function' ? editor.getValue() : '';
  })).toContain('"network": "udp"');

  await replaceRoutingText(page, UNKNOWN_RULE_FIELD_ROUTING);
  await waitForRoutingSchema(page);
  await expect
    .poll(() => page.evaluate(() => document.querySelectorAll('.cm-lintRange-warning, .cm-lint-marker-warning').length))
    .toBeGreaterThan(0);
  await page.locator('.cm-lintRange-warning, .cm-lint-marker-warning').first().hover();
  await expect(page.locator('.cm-tooltip-lint')).toContainText('portt');
  await expect(page.locator('.cm-tooltip-lint')).toContainText('не разрешено');
  await setSchemaHoverEnabled(page, true);
  await clearEditorTooltips(page);

  await saveSchemaHoverEnabled(page, false);
  await page.reload();
  await waitForRoutingEditor(page);
  await ensureCodeMirrorRouting(page);
  await waitForRoutingSchema(page);
  await waitForUiSettings(page);
  await replaceRoutingText(page, SUBSCRIPTION_ROUTING);
  await clearEditorTooltips(page);
  await hoverRenderedToken(page, '"rules"');
  await page.waitForTimeout(700);
  await expect.poll(() => page.evaluate(() => document.querySelectorAll('.cm-tooltip-hover, .cm6-json-schema-hover').length)).toBe(0);
  await saveSchemaHoverEnabled(page, true);
});
