#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path


RAW_BUILD_MANIFEST_REL = Path("xkeen-ui/static/frontend-build/.vite/manifest.build.json")
BRIDGE_MANIFEST_REL = Path("xkeen-ui/static/frontend-build/.vite/manifest.json")
BUILD_ROOT_REL = Path("xkeen-ui/static/frontend-build")

ENTRIES = {
    "panel": "js/pages/panel.entry.js",
    "xkeen": "js/pages/xkeen.entry.js",
    "backups": "js/pages/backups.entry.js",
    "devtools": "js/pages/devtools.entry.js",
    "mihomo_generator": "js/pages/mihomo_generator.entry.js",
}


def find_repo_root(start: Path) -> Path:
    start = start.resolve()
    for candidate in [start, *start.parents]:
        if (candidate / "xkeen-ui").is_dir() and (candidate / RAW_BUILD_MANIFEST_REL).is_file():
            return candidate
    raise FileNotFoundError(
        f"Could not find repository root containing {RAW_BUILD_MANIFEST_REL}"
    )


def sync_bridge_manifest(repo_root: Path) -> int:
    build_root = repo_root / BUILD_ROOT_REL
    vite_dir = build_root / ".vite"
    assets_dir = build_root / "assets"
    raw_manifest = repo_root / RAW_BUILD_MANIFEST_REL
    bridge_manifest = repo_root / BRIDGE_MANIFEST_REL

    if not raw_manifest.is_file():
        raise FileNotFoundError(
            f"Missing raw build manifest: {raw_manifest}. Run 'npm run frontend:build' first."
        )

    vite_dir.mkdir(parents=True, exist_ok=True)
    assets_dir.mkdir(parents=True, exist_ok=True)

    manifest: dict[str, dict[str, object]] = {}

    for name, src in ENTRIES.items():
        wrapper_file = f"assets/{name}-bridge.js"
        manifest[f"static/{src}"] = {
            "file": wrapper_file,
            "isEntry": True,
            "name": name,
            "src": f"static/{src}",
        }

        (build_root / wrapper_file).write_text(
            "\n".join(
                [
                    "// Auto-generated by scripts/sync_frontend_build_manifest.py",
                    "// Build-managed ESM bridge entry. The canonical module graph lives under static/js.",
                    f"import '../../{src}';",
                    "",
                ]
            ),
            encoding="utf-8",
        )

    bridge_manifest.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )

    print(f"Wrote {bridge_manifest} with {len(manifest)} entries")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--repo-root", default=".")
    args = parser.parse_args()

    repo_root = find_repo_root(Path(args.repo_root))
    return sync_bridge_manifest(repo_root)


if __name__ == "__main__":
    raise SystemExit(main())
