from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_DIRNAME = "xkeen-ui"
MANIFEST_RELATIVE_PATH = Path("static/frontend-build/.vite/manifest.json")
WRAPPER_HEADER = "// Auto-generated by scripts/sync_frontend_build_manifest.py"
WRAPPER_SUBHEADER = "// Build-managed ESM bridge entry. The canonical module graph lives under static/js."
CANONICAL_PAGE_PREFIX = "static/js/pages/"


@dataclass(frozen=True)
class WrapperSpec:
    source_entry: str
    build_file: str

    @property
    def wrapper_text(self) -> str:
        source_path = Path(self.source_entry)
        build_path = Path(self.build_file)
        build_dir = Path(PROJECT_DIRNAME) / "static" / "frontend-build" / build_path.parent
        source_fs_path = Path(PROJECT_DIRNAME) / source_path
        import_path = _relative_import(build_dir, source_fs_path)
        return "\n".join(
            [
                WRAPPER_HEADER,
                WRAPPER_SUBHEADER,
                f"import '{import_path}';",
                "",
            ]
        )


def _relative_import(from_dir: Path, target_file: Path) -> str:
    rel = Path(os.path.relpath(str(target_file), str(from_dir))).as_posix()
    if not rel.startswith("."):
        rel = f"./{rel}"
    return rel


def _find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / PROJECT_DIRNAME).is_dir() and (candidate / PROJECT_DIRNAME / MANIFEST_RELATIVE_PATH).is_file():
            return candidate
    raise FileNotFoundError(
        f"Could not find repository root containing {PROJECT_DIRNAME}/{MANIFEST_RELATIVE_PATH.as_posix()}"
    )


def load_manifest(repo_root: Path) -> dict[str, dict[str, object]]:
    manifest_path = repo_root / PROJECT_DIRNAME / MANIFEST_RELATIVE_PATH
    with manifest_path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError("frontend build manifest must be a JSON object")
    return data


def collect_wrapper_specs(manifest: dict[str, dict[str, object]]) -> list[WrapperSpec]:
    specs: list[WrapperSpec] = []
    seen_build_files: set[str] = set()
    for source_entry, payload in manifest.items():
        if not source_entry.startswith(CANONICAL_PAGE_PREFIX):
            continue
        if not isinstance(payload, dict):
            raise ValueError(f"manifest entry for {source_entry!r} must be an object")
        if payload.get("isEntry") is not True:
            continue
        build_file = str(payload.get("file") or "").strip()
        if not build_file:
            raise ValueError(f"manifest entry for {source_entry!r} is missing file")
        if not build_file.startswith("assets/") or not build_file.endswith(".js"):
            raise ValueError(f"manifest entry for {source_entry!r} must point to a JS asset under assets/: {build_file!r}")
        if build_file in seen_build_files:
            raise ValueError(f"duplicate build wrapper target in manifest: {build_file}")
        seen_build_files.add(build_file)
        specs.append(WrapperSpec(source_entry=source_entry, build_file=build_file))
    specs.sort(key=lambda item: item.source_entry)
    return specs


def sync_manifest_wrappers(repo_root: Path, *, check: bool = False, stdout: object | None = None) -> int:
    stream = stdout if stdout is not None else sys.stdout
    manifest = load_manifest(repo_root)
    specs = collect_wrapper_specs(manifest)

    if not specs:
        raise ValueError("manifest does not contain any canonical page entry wrappers to sync")

    changed_paths: list[Path] = []
    for spec in specs:
        wrapper_path = repo_root / PROJECT_DIRNAME / "static" / "frontend-build" / spec.build_file
        wrapper_path.parent.mkdir(parents=True, exist_ok=True)
        expected = spec.wrapper_text
        current = wrapper_path.read_text(encoding="utf-8") if wrapper_path.is_file() else None
        if current == expected:
            print(f"OK {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)
            continue
        changed_paths.append(wrapper_path)
        if check:
            print(f"MISMATCH {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)
            continue
        wrapper_path.write_text(expected, encoding="utf-8")
        print(f"UPDATED {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)

    if check and changed_paths:
        print(f"Wrapper sync check failed for {len(changed_paths)} file(s).", file=stream)
        return 1

    print(f"Synced {len(specs)} wrapper file(s).", file=stream)
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Sync thin frontend build wrappers from static/frontend-build/.vite/manifest.json"
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root containing xkeen-ui/ (defaults to auto-detect from the current working directory)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero instead of writing files when a wrapper differs from the manifest-derived canonical content.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    repo_root = _find_repo_root(args.repo_root or Path.cwd())
    return sync_manifest_wrappers(repo_root, check=bool(args.check))


if __name__ == "__main__":
    raise SystemExit(main())
