from __future__ import annotations

import argparse
import json
import os
import sys
from dataclasses import dataclass
from pathlib import Path


PROJECT_DIRNAME = "xkeen-ui"
RAW_MANIFEST_RELATIVE_PATH = Path("static/frontend-build/.vite/manifest.build.json")
BRIDGE_MANIFEST_RELATIVE_PATH = Path("static/frontend-build/.vite/manifest.json")
BUILD_ROOT_RELATIVE_PATH = Path("static/frontend-build")
RAW_MANIFEST_BUILD_PATH = Path(".vite/manifest.build.json")
BRIDGE_MANIFEST_BUILD_PATH = Path(".vite/manifest.json")
WRAPPER_HEADER = "// Auto-generated by scripts/sync_frontend_build_manifest.py"
WRAPPER_SUBHEADER = "// Build-managed ESM bridge entry. The canonical module graph lives under static/js."
RAW_PAGE_PREFIX = "js/pages/"
BRIDGE_PAGE_PREFIX = "static/js/pages/"
MANIFEST_FILE_LIST_KEYS = ("imports", "dynamicImports", "css", "assets")


@dataclass(frozen=True)
class WrapperSpec:
    source_entry: str
    build_file: str
    page_name: str

    @property
    def wrapper_text(self) -> str:
        source_path = Path(self.source_entry)
        build_path = Path(self.build_file)
        build_dir = Path(PROJECT_DIRNAME) / "static" / "frontend-build" / build_path.parent
        source_fs_path = Path(PROJECT_DIRNAME) / source_path
        import_path = _relative_import(build_dir, source_fs_path)
        return "\n".join(
            [
                WRAPPER_HEADER,
                WRAPPER_SUBHEADER,
                f"import '{import_path}';",
                "",
            ]
        )

    @property
    def bridge_manifest_entry(self) -> dict[str, object]:
        return {
            "file": self.build_file,
            "isEntry": True,
            "name": self.page_name,
            "src": self.source_entry,
        }


@dataclass(frozen=True)
class LoadedManifest:
    path: Path
    data: dict[str, dict[str, object]]
    kind: str  # "raw" or "bridge"


def _relative_import(from_dir: Path, target_file: Path) -> str:
    rel = Path(os.path.relpath(str(target_file), str(from_dir))).as_posix()
    if not rel.startswith("."):
        rel = f"./{rel}"
    return rel


def _find_repo_root(start: Path) -> Path:
    current = start.resolve()
    for candidate in (current, *current.parents):
        if (candidate / PROJECT_DIRNAME).is_dir():
            return candidate
    raise FileNotFoundError(f"Could not find repository root containing {PROJECT_DIRNAME}/")


def load_manifest(repo_root: Path) -> LoadedManifest:
    raw_path = repo_root / PROJECT_DIRNAME / RAW_MANIFEST_RELATIVE_PATH
    bridge_path = repo_root / PROJECT_DIRNAME / BRIDGE_MANIFEST_RELATIVE_PATH

    if raw_path.is_file():
        chosen_path = raw_path
        kind = "raw"
    elif bridge_path.is_file():
        chosen_path = bridge_path
        kind = "bridge"
    else:
        raise FileNotFoundError(
            "Could not find frontend build manifest at "
            f"{PROJECT_DIRNAME}/{RAW_MANIFEST_RELATIVE_PATH.as_posix()} or "
            f"{PROJECT_DIRNAME}/{BRIDGE_MANIFEST_RELATIVE_PATH.as_posix()}"
        )

    with chosen_path.open("r", encoding="utf-8") as fh:
        data = json.load(fh)
    if not isinstance(data, dict):
        raise ValueError("frontend build manifest must be a JSON object")
    return LoadedManifest(path=chosen_path, data=data, kind=kind)


def _bridge_source_entry(raw_source_entry: str) -> str:
    return f"static/{raw_source_entry}" if not raw_source_entry.startswith("static/") else raw_source_entry


def _bridge_asset_filename(raw_source_entry: str, payload: dict[str, object]) -> str:
    page_name = str(payload.get("name") or "").strip()
    if not page_name:
        filename = Path(raw_source_entry).name
        if filename.endswith(".entry.js"):
            page_name = filename[: -len(".entry.js")]
        else:
            page_name = Path(raw_source_entry).stem
    return f"assets/{page_name}-bridge.js"


def _page_name_from_source(source_entry: str, payload: dict[str, object]) -> str:
    page_name = str(payload.get("name") or "").strip()
    if page_name:
        return page_name
    filename = Path(source_entry).name
    if filename.endswith(".entry.js"):
        return filename[: -len(".entry.js")]
    return Path(source_entry).stem


def collect_wrapper_specs(manifest: dict[str, dict[str, object]], *, kind: str) -> list[WrapperSpec]:
    specs: list[WrapperSpec] = []
    seen_build_files: set[str] = set()
    expected_prefix = RAW_PAGE_PREFIX if kind == "raw" else BRIDGE_PAGE_PREFIX

    for source_entry_in_manifest, payload in manifest.items():
        if not source_entry_in_manifest.startswith(expected_prefix):
            continue
        if not isinstance(payload, dict):
            raise ValueError(f"manifest entry for {source_entry_in_manifest!r} must be an object")
        if payload.get("isEntry") is not True:
            continue

        if kind == "raw":
            source_entry = _bridge_source_entry(source_entry_in_manifest)
            build_file = _bridge_asset_filename(source_entry_in_manifest, payload)
        else:
            source_entry = source_entry_in_manifest
            build_file = str(payload.get("file") or "").strip()
            if not build_file:
                raise ValueError(f"manifest entry for {source_entry_in_manifest!r} is missing file")

        if build_file in seen_build_files:
            raise ValueError(f"duplicate build wrapper target in manifest: {build_file}")
        seen_build_files.add(build_file)
        page_name = _page_name_from_source(source_entry_in_manifest, payload)
        specs.append(WrapperSpec(source_entry=source_entry, build_file=build_file, page_name=page_name))

    specs.sort(key=lambda item: item.source_entry)
    return specs


def build_bridge_manifest(specs: list[WrapperSpec]) -> dict[str, dict[str, object]]:
    return {spec.source_entry: spec.bridge_manifest_entry for spec in specs}


def _json_text(data: dict[str, dict[str, object]]) -> str:
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def _normalize_build_relative_path(value: object) -> str | None:
    raw = str(value or "").strip().replace("\\", "/").lstrip("/")
    return raw or None


def _manifest_file_refs(manifest: dict[str, dict[str, object]]) -> set[str]:
    refs: set[str] = set()
    for payload in manifest.values():
        if not isinstance(payload, dict):
            continue
        build_file = _normalize_build_relative_path(payload.get("file"))
        if build_file:
            refs.add(build_file)
        for key in MANIFEST_FILE_LIST_KEYS:
            value = payload.get(key)
            if not isinstance(value, list):
                continue
            for entry in value:
                normalized = _normalize_build_relative_path(entry)
                if normalized:
                    refs.add(normalized)
    return refs


def prune_stale_build_files(
    repo_root: Path,
    *,
    loaded: LoadedManifest,
    specs: list[WrapperSpec],
    check: bool = False,
    stdout: object | None = None,
) -> int:
    stream = stdout if stdout is not None else sys.stdout
    build_root = repo_root / PROJECT_DIRNAME / BUILD_ROOT_RELATIVE_PATH
    raw_manifest_path = repo_root / PROJECT_DIRNAME / RAW_MANIFEST_RELATIVE_PATH
    bridge_manifest_path = repo_root / PROJECT_DIRNAME / BRIDGE_MANIFEST_RELATIVE_PATH

    if loaded.kind != "raw" or not raw_manifest_path.is_file():
        print(
            "SKIP prune (raw manifest missing; keeping existing frontend-build files as-is)",
            file=stream,
        )
        return 0

    keep_paths: set[str] = {
        RAW_MANIFEST_BUILD_PATH.as_posix(),
        BRIDGE_MANIFEST_BUILD_PATH.as_posix(),
    }
    keep_paths.update(spec.build_file for spec in specs)
    keep_paths.update(_manifest_file_refs(loaded.data))

    stale_paths: list[Path] = []
    for path in sorted(build_root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
        if not path.is_file():
            continue
        rel = path.relative_to(build_root).as_posix()
        if rel in keep_paths:
            continue
        stale_paths.append(path)

    if not stale_paths:
        print("OK no stale frontend-build files", file=stream)
        return 0

    for path in stale_paths:
        rel = path.relative_to(repo_root).as_posix()
        if check:
            print(f"STALE {rel}", file=stream)
            continue
        path.unlink()
        print(f"REMOVED {rel}", file=stream)

    if not check:
        for path in sorted(build_root.rglob("*"), key=lambda item: len(item.parts), reverse=True):
            if not path.is_dir():
                continue
            try:
                next(path.iterdir())
            except StopIteration:
                path.rmdir()

    if check:
        print(f"Prune check failed for {len(stale_paths)} stale file(s).", file=stream)
        return 1

    print(f"Pruned {len(stale_paths)} stale frontend-build file(s).", file=stream)
    return 0


def sync_manifest_wrappers(repo_root: Path, *, check: bool = False, stdout: object | None = None) -> int:
    stream = stdout if stdout is not None else sys.stdout
    loaded = load_manifest(repo_root)
    specs = collect_wrapper_specs(loaded.data, kind=loaded.kind)

    if not specs:
        raise ValueError("manifest does not contain any canonical page entry wrappers to sync")

    changed_paths: list[Path] = []

    bridge_manifest_path = repo_root / PROJECT_DIRNAME / BRIDGE_MANIFEST_RELATIVE_PATH
    expected_manifest_text = _json_text(build_bridge_manifest(specs))
    current_manifest_text = bridge_manifest_path.read_text(encoding="utf-8") if bridge_manifest_path.is_file() else None
    if current_manifest_text != expected_manifest_text:
        changed_paths.append(bridge_manifest_path)
        if check:
            print(f"MISMATCH {bridge_manifest_path.relative_to(repo_root).as_posix()}", file=stream)
        else:
            bridge_manifest_path.parent.mkdir(parents=True, exist_ok=True)
            bridge_manifest_path.write_text(expected_manifest_text, encoding="utf-8")
            print(f"UPDATED {bridge_manifest_path.relative_to(repo_root).as_posix()}", file=stream)
    else:
        print(f"OK {bridge_manifest_path.relative_to(repo_root).as_posix()}", file=stream)

    for spec in specs:
        wrapper_path = repo_root / PROJECT_DIRNAME / "static" / "frontend-build" / spec.build_file
        wrapper_path.parent.mkdir(parents=True, exist_ok=True)
        expected = spec.wrapper_text
        current = wrapper_path.read_text(encoding="utf-8") if wrapper_path.is_file() else None
        if current == expected:
            print(f"OK {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)
            continue
        changed_paths.append(wrapper_path)
        if check:
            print(f"MISMATCH {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)
            continue
        wrapper_path.write_text(expected, encoding="utf-8")
        print(f"UPDATED {wrapper_path.relative_to(repo_root).as_posix()}", file=stream)

    if check and changed_paths:
        print(f"Wrapper sync check failed for {len(changed_paths)} file(s).", file=stream)
        return 1

    print(f"Synced {len(specs)} wrapper file(s).", file=stream)
    return prune_stale_build_files(repo_root, loaded=loaded, specs=specs, check=check, stdout=stream)


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=(
            "Sync bridge frontend build wrappers from Vite raw manifest.build.json or existing bridge manifest.json "
            "to manifest.json + assets/*-bridge.js"
        )
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=None,
        help="Repository root containing xkeen-ui/ (defaults to auto-detect from the current working directory)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero instead of writing files when a wrapper differs from the manifest-derived canonical content.",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_arg_parser()
    args = parser.parse_args(argv)

    repo_root = _find_repo_root(args.repo_root or Path.cwd())
    return sync_manifest_wrappers(repo_root, check=bool(args.check))


if __name__ == "__main__":
    raise SystemExit(main())
