import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const repoRoot = path.resolve(__dirname, '..');
const projectRoot = path.join(repoRoot, 'xkeen-ui');
const buildRoot = path.join(projectRoot, 'static', 'frontend-build');
const vendorRoot = path.join(projectRoot, 'static', 'vendor');
const bridgeManifestPath = path.join(buildRoot, '.vite', 'manifest.json');
const buildManifestPath = path.join(buildRoot, '.vite', 'manifest.build.json');
const codemirrorImportmapTemplatePath = path.join(projectRoot, 'templates', '_codemirror6_importmap.html');

const WRAPPER_HEADER = '// Auto-generated by scripts/sync_frontend_build_manifest.py';
const WRAPPER_SUBHEADER = '// Build-managed ESM bridge entry. The canonical module graph lives under static/js.';
const REQUIRED_PRETTIER_VENDOR_FILES = [
  'prettier/standalone.js',
  'prettier/plugins/babel.js',
  'prettier/plugins/estree.js',
  'prettier/plugins/yaml.js',
];

const EXPECTED_PAGE_ENTRIES = {
  panel: 'js/pages/panel.entry.js',
  xkeen: 'js/pages/xkeen.entry.js',
  backups: 'js/pages/backups.entry.js',
  devtools: 'js/pages/devtools.entry.js',
  mihomo_generator: 'js/pages/mihomo_generator.entry.js',
};

function fail(message) {
  throw new Error(message);
}

function readJson(filePath, label) {
  if (!fs.existsSync(filePath)) {
    fail(`${label} is missing: ${path.relative(repoRoot, filePath)}`);
  }
  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch (error) {
    fail(`${label} is not valid JSON: ${path.relative(repoRoot, filePath)}\n${error}`);
  }
}

function assert(condition, message) {
  if (!condition) fail(message);
}

function collectRequiredVendorFiles() {
  const template = fs.readFileSync(codemirrorImportmapTemplatePath, 'utf8');
  const importmapRefs = Array.from(template.matchAll(/vendor\/npm\/([^"']+)/g)).map((match) => `npm/${match[1]}`);
  const refs = new Set([...importmapRefs, ...REQUIRED_PRETTIER_VENDOR_FILES]);
  refs.add('npm/manifest.json');
  return Array.from(refs).sort();
}

function verifyBridgeManifest() {
  const manifest = readJson(bridgeManifestPath, 'Bridge manifest');
  const expectedKeys = Object.entries(EXPECTED_PAGE_ENTRIES).map(([, source]) => `static/${source}`);
  assert(JSON.stringify(Object.keys(manifest).sort()) === JSON.stringify(expectedKeys.sort()), 'bridge manifest keys drifted away from the canonical source entry set');

  for (const [entryName, sourceEntry] of Object.entries(EXPECTED_PAGE_ENTRIES)) {
    const manifestKey = `static/${sourceEntry}`;
    const payload = manifest[manifestKey];
    assert(payload && typeof payload === 'object', `bridge manifest entry missing for ${entryName}`);
    assert(payload.isEntry === true, `bridge manifest entry for ${entryName} must stay marked as isEntry`);
    assert(payload.name === entryName, `bridge manifest entry for ${entryName} must keep its canonical page name`);
    assert(payload.src === manifestKey, `bridge manifest entry for ${entryName} must keep src=${manifestKey}`);

    const buildFile = String(payload.file || '').trim();
    assert(buildFile.startsWith(`assets/${entryName}-`) && buildFile.endsWith('.js'), `bridge wrapper filename for ${entryName} must stay under assets/${entryName}-*.js`);

    const wrapperPath = path.join(buildRoot, buildFile);
    assert(fs.existsSync(wrapperPath), `bridge wrapper is missing for ${entryName}: ${path.relative(repoRoot, wrapperPath)}`);

    const text = fs.readFileSync(wrapperPath, 'utf8');
    const statements = text.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !line.startsWith('//'));
    assert(text.includes(WRAPPER_HEADER), `${entryName} bridge wrapper must advertise sync ownership`);
    assert(text.includes(WRAPPER_SUBHEADER), `${entryName} bridge wrapper must advertise the stage-3 bridge contract`);
    assert(statements.length === 1 && statements[0] === `import '../../${sourceEntry}';`, `${entryName} bridge wrapper must be import-only and point to the canonical source entry`);
  }
}

function verifyBuildManifest() {
  const manifest = readJson(buildManifestPath, 'Raw Vite build manifest');

  for (const [entryName, sourceEntry] of Object.entries(EXPECTED_PAGE_ENTRIES)) {
    const payload = manifest[sourceEntry];
    assert(payload && typeof payload === 'object', `raw build manifest entry missing for ${entryName}`);
    assert(payload.isEntry === true, `raw build manifest entry for ${entryName} must stay marked as isEntry`);
    assert(payload.name === entryName, `raw build manifest entry for ${entryName} must keep its canonical page name`);
    assert(payload.src === sourceEntry, `raw build manifest entry for ${entryName} must keep src=${sourceEntry}`);

    const buildFile = String(payload.file || '').trim();
    assert(buildFile.startsWith(`assets/${entryName}-`) && buildFile.endsWith('.js'), `raw build manifest file for ${entryName} must stay under assets/${entryName}-*.js`);

    const assetPath = path.join(buildRoot, buildFile);
    assert(fs.existsSync(assetPath), `raw build asset is missing for ${entryName}: ${path.relative(repoRoot, assetPath)}`);
    assert(fs.statSync(assetPath).size > 0, `raw build asset for ${entryName} must not be empty`);
  }
}

function normalizeBuildPath(value) {
  const raw = String(value || '').trim().replace(/\\/g, '/').replace(/^\/+/, '');
  return raw || null;
}

function collectManifestFileRefs(manifest) {
  const refs = new Set();
  for (const payload of Object.values(manifest || {})) {
    if (!payload || typeof payload !== 'object') continue;
    const buildFile = normalizeBuildPath(payload.file);
    if (buildFile) refs.add(buildFile);
    for (const key of ['imports', 'dynamicImports', 'css', 'assets']) {
      const value = payload[key];
      if (!Array.isArray(value)) continue;
      for (const entry of value) {
        const normalized = normalizeBuildPath(entry);
        if (normalized) refs.add(normalized);
      }
    }
  }
  return refs;
}

function verifyNoStaleBuildFiles() {
  const rawManifest = readJson(buildManifestPath, 'Raw Vite build manifest');
  const bridgeManifest = readJson(bridgeManifestPath, 'Bridge manifest');
  const keep = new Set([
    '.vite/manifest.build.json',
    '.vite/manifest.json',
  ]);

  for (const rel of collectManifestFileRefs(rawManifest)) keep.add(rel);
  for (const payload of Object.values(bridgeManifest || {})) {
    if (!payload || typeof payload !== 'object') continue;
    const buildFile = normalizeBuildPath(payload.file);
    if (buildFile) keep.add(buildFile);
  }

  const allFiles = [];
  const stack = [buildRoot];
  while (stack.length) {
    const current = stack.pop();
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const fullPath = path.join(current, entry.name);
      if (entry.isDirectory()) {
        stack.push(fullPath);
        continue;
      }
      if (!entry.isFile()) continue;
      allFiles.push(path.relative(buildRoot, fullPath).replace(/\\/g, '/'));
    }
  }

  const stale = allFiles.filter((rel) => !keep.has(rel));
  assert(stale.length === 0, `frontend build contains stale files not referenced by current manifests:\n${stale.slice(0, 20).join('\n')}`);
}

function verifyVendorAssets() {
  assert(fs.existsSync(codemirrorImportmapTemplatePath), `CodeMirror importmap template is missing: ${path.relative(repoRoot, codemirrorImportmapTemplatePath)}`);
  assert(fs.existsSync(vendorRoot), `frontend vendor directory is missing: ${path.relative(repoRoot, vendorRoot)}`);

  const missing = [];
  for (const rel of collectRequiredVendorFiles()) {
    const fullPath = path.join(vendorRoot, rel);
    if (!fs.existsSync(fullPath)) {
      missing.push(rel);
      continue;
    }
    if (fs.statSync(fullPath).isFile() && fs.statSync(fullPath).size <= 0) {
      missing.push(`${rel} (empty)`);
    }
  }

  assert(missing.length === 0, `frontend vendor assets are missing or empty:\n${missing.join('\n')}`);
}

verifyBridgeManifest();
verifyBuildManifest();
verifyNoStaleBuildFiles();
verifyVendorAssets();
console.log('Frontend build bridge + raw build manifests verified, including required vendor assets.');
